name: Unit tests

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

  workflow_dispatch:

jobs:
  build:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Unit tests - Core
        run: cd core && ../gradlew test

      - name: Unit tests - Android
        run: cd android && ../gradlew test

      - name: Unit tests - Ktor
        run: cd ktor && ../gradlew test
